Defer heavier Data Validation until a world is actually used
ManualForArchipelago/Manual pull request #24
Opened 2024-03-08 23:40 UTC by silasary

We currently run the entire test suite against every installed manual world regardless of whether they're in use.  This is bad for AP load times, even when not using Manual.

This moves the heavier stuff into the generator, so we don't run as much during Launcher startup.

It also sneaks in a couple of changes that have been sitting in my working directory for the better part of a month:
- Type hints for dictionaries in Location.py
- Hook for writing to the spoiler log

2024-03-08 23:52 UTC, nicopop submitted a review, later dismissed
looks good, ill definetly need to try that spoiler hook and replace my hacky use of options to write stuff to the spoilers xD

2024-03-09 00:40 UTC, FuzzyGamesOn requested changes

2024-03-09 00:44 UTC, silasary commented on src/__init__.py
> +    def stage_write_spoiler(cls, multiworld, spoiler_handle):
Uhh, no. I guess I just looked at the wrong world when figuring out how to do it 😅

2024-03-09 00:47 UTC, FuzzyGamesOn approved these changes

2024-03-09 00:47 UTC, merged