Breaking change: Moving item creation to the create_items step
ManualForArchipelago/Manual pull request #7
Opened 2024-01-22 04:07 UTC by FuzzyGamesOn

This is something that's needed to be adjusted for a while. Currently, Manual creates its item pool in generate_basic, but it really should be created in create_items, since that's what it's there for. generate_basic is more there for post item pool things.

So this PR changes that. Some of the specific changes:
- There are now two hooks to replace before_generate_basic: before_create_items_starting and before_create_items_filler
   - That way, people can hook before whichever process they want during item creation
- The victory location and its event are now setup during create_regions instead of pre_fill, as another "what it's there for" change
- generate_basic now just handles place and don't place.

Updated all the hook templates and created new hooks for create_items, and took item pool out of generate basic hooks.

(As an aside, took out progressive items, since they were never implemented.)

2024-01-22 13:33 UTC, silasary requested changes
Looks good, other than a couple minor tweaks

2024-01-22 13:33 UTC, silasary commented on src/__init__.py
> +            item_count = int(item.get("count") or 1)
This will increase `"count": 0` to 1.
You want to use `item.get("count", 1)`.

2024-01-22 13:33 UTC, silasary commented on src/__init__.py
> +    ###
If I'm going to be technical, `generate_output` is a standard method

2024-01-22 15:47 UTC, FuzzyGamesOn commented
> Looks good, other than a couple minor tweaks

Yep, got those sorted. Thanks for pointing those out! 😁 Forgot about generate_output down there, haha.

2024-01-22 17:07 UTC, nicopop approved these changes
looks good, ill need to modify stuff on my pr once this merge but this should work

2024-01-23 04:47 UTC, silasary approved these changes

2024-01-23 04:52 UTC, merged