Add `yaml_option` support to starting_items
ManualForArchipelago/Manual pull request #71
Opened 2024-07-21 06:48 UTC by silasary

Literally the same syntax as categories.json

2024-07-21 17:54 UTC, nicopop requested changes
other than this small definition, looks good

2024-07-21 17:54 UTC, nicopop commented on schemas/Manual.game.schema.json
> +                    "description": "(Optional) Array of Options that will decide if the items & locations in this category are enabled",
```suggestion
                    "description": "(Optional) Array of Options that will decide if this block is rolled",
```

2024-07-21 17:56 UTC, nicopop commented on schemas/Manual.game.schema.json
> +                    "description": "(Optional) Array of Options that will decide if the items & locations in this category are enabled",
oops forgot to add the why for this sugested change:
in startinv if you look in the other defs you can see that its starting_items's blocks we define not items & locations

2024-09-17 23:54 UTC, FuzzyGamesOn submitted a review, later dismissed

2024-09-17 23:54 UTC, FuzzyGamesOn commented
Looks fine. Just needs the merge conflict resolved 😃

2024-09-19 17:22 UTC, FuzzyGamesOn approved these changes

2024-09-19 21:07 UTC, nicopop approved these changes

2024-09-19 22:29 UTC, merged