DRAFT Validating data tables against their schema
ManualForArchipelago/Manual pull request #82
Opened 2024-09-20 00:00 UTC by nicopop

im opening a draft pr to know if this is something we would want to do.

This pr implement actually verifiying each files from data/ with their json schema.
There's one big issue with that, it requires the jsonschema library (and its required packaged)
- Good news, all of those uses the MIT license
- Bad news as of writing this Archipelago does not allow world to have their own libary requirements so the only way to use them is to vendorize them.

Currently, in the pr I didnt include the vendorized version of the libraries and they do need some tweeks to work correctly
but I didnt want to push 1,05 Mo of libraries if this is abandonded

Also to help with circular import I moved "clean" function/methodes in a new Utils.py with no imports of other files from Manual

2024-09-20 00:40 UTC, FuzzyGamesOn commented
I guess my main question is: Why would we want this? What problem is it solving, or purpose is it serving?

2024-09-20 01:39 UTC, silasary commented
Not a fan of this

2024-09-28 23:57 UTC, silasary requested changes
To clarify my thoughts, I have two problems with this.

1. Hook developers can and do extend the json with extra data. The jsonschema does not like unknown fields, and will fail over the them.
2. This involves making multiple web requests during generation, often on the machine of a person who is neither the APWorld dev, nor the player playing the game. While this isn't technically a problem, some users will view it as a red flag, and might ban manuals from their games because of it. 

I do not want to merge this.

2024-09-28 23:59 UTC, nicopop commented
> To clarify my thoughts, I have two problems with this.
> 
> 1. Hook developers can and do extend the json with extra data. The jsonschema does not like unknown fields, and will fail over the them.
> 2. This involves making multiple web requests during generation, often on the machine of a person who is neither the APWorld dev, nor the player playing the game. While this isn't technically a problem, some users will view it as a red flag, and might ban manuals from their games because of it.
> 
> I do not want to merge this.
@silasary 
fair enough it was more of a proof of concept born out of an hyperfocus, there some stuff in there I liked and will probably recycle but the rest will go

2024-09-28 23:59 UTC, closed without merging

2024-09-29 00:05 UTC, silasary commented
Yeah, it's really cool, and would make for a useful external tool. But it doesn't belong in DV

2024-11-27 00:45 UTC, silasary commented
Am I good to steal this code? I have a use for it :D